AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:

  ArtifactsBucket:
    Type: String

  EmailError:
    Type: String

Resources:
  
  EMRClusterServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "elasticmapreduce.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole
      Tags:
        - Key: Example
          Value: !Ref AWS::StackName

  EMRClusterinstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role

  EMRClusterinstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EMRClusterinstanceProfileRole

  EMRClusterLogs:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Example
          Value: !Ref AWS::StackName

  SNSError:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: "email"
          Endpoint: !Ref EmailError
      Tags:
        - Key: Example
          Value: !Ref AWS::StackName

  GetParamsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      CodeUri: ./src/get_params/
      Handler: lambda_function.lambda_handler
      Timeout: 900
      Environment:
        Variables:
          CLUSTER_NAME: !Ref "AWS::StackName"
          SNS_ERROR: !Ref SNSError
          STACK_NAME: !Ref AWS::StackName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'elasticmapreduce:ListClusters'
              Resource: '*'
      Tags:
        Example: !Ref AWS::StackName

  GetStepCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      CodeUri: ./src/get_step_count/
      Handler: lambda_function.lambda_handler
      Timeout: 900
      Environment:
        Variables:
          SNS_ERROR: !Ref SNSError
          STACK_NAME: !Ref AWS::StackName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'elasticmapreduce:ListSteps'
              Resource: '*'
      Tags:
        Example: !Ref AWS::StackName

  GetStepExistsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      CodeUri: ./src/get_step_exists/
      Handler: lambda_function.lambda_handler
      Timeout: 900
      Environment:
        Variables:
          SNS_ERROR: !Ref SNSError
          STACK_NAME: !Ref AWS::StackName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'elasticmapreduce:ListSteps'
              Resource: '*'
      Tags:
        Example: !Ref AWS::StackName

  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "states.amazonaws.com"
      Policies:
        - PolicyName: StateMachinePermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "lambda:InvokeFunction"
                Resource:
                  - !Sub "${GetParamsFunction.Arn}"
                  - !Sub "${GetStepCountFunction.Arn}"
                  - !Sub "${GetStepExistsFunction.Arn}"
              - Effect: Allow
                Action:
                  - "elasticmapreduce:AddJobFlowSteps"
                  - "elasticmapreduce:DescribeCluster"
                  - "elasticmapreduce:DescribeStep"
                  - "elasticmapreduce:RunJobFlow"
                  - "elasticmapreduce:TerminateJobFlows"
                Resource: !Sub "arn:aws:elasticmapreduce:${AWS::Region}:${AWS::AccountId}:cluster/*"
              - Effect: Allow
                Action: "iam:PassRole"
                Resource:
                  - !Sub ${EMRClusterServiceRole.Arn}
                  - !Sub ${EMRClusterinstanceProfileRole.Arn}
              - Effect: Allow
                Action: "sns:Publish"
                Resource: !Sub "${SNSError}"
      Tags:
        - Key: Example
          Value: !Ref AWS::StackName

  StepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Ref "AWS::StackName"
      DefinitionString: !Sub |-
        {
          "StartAt": "Get Params",
          "States": {
            
            "Get Params": {
              "Type": "Task",
              "Resource": "${GetParamsFunction.Arn}",
              "Catch": [{
                "ErrorEquals": ["States.TaskFailed"],
                "Next": "Log Error"
              }],
              "Next": "Check Params"
            },

            "Check Params": {
              "Type": "Choice",
              "Choices": [{
                "Variable": "$.Error",
                "IsPresent": true,
                "Next": "Fail GetParams"
              },{
                "Variable": "$.Cluster.ClusterId",
                "StringEquals": "",
                "Next": "Create Cluster"
              }],
              "Default": "Get StepExists"
            },

            "Fail GetParams": {
              "Type": "Fail",
              "Error": "Get Params",
              "Cause": "Please, check the EMAIL for error message."
            },

            "Create Cluster": {
              "Type": "Task",
              "Resource": "arn:aws:states:::elasticmapreduce:createCluster",
              "Parameters": {
                "Name": "${AWS::StackName}",
                "ReleaseLabel": "emr-5.30.1",
                "Applications": [
                  { "Name": "Spark" }
                ],
                "BootstrapActions": [{
                  "Name": "install_libs",
                  "ScriptBootstrapAction": { "Path": "s3://${ArtifactsBucket}/install_libs.sh" }
                }],
                "Configurations":[
                  {
                    "Classification":"hive-site",
                    "Properties":{
                      "hive.metastore.client.factory.class":"com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory"
                    }
                  },{
                    "Classification":"spark-hive-site",
                    "Properties":{
                      "hive.metastore.client.factory.class":"com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory"
                    }
                  }
                ],
                "Instances": {
                  "KeepJobFlowAliveWhenNoSteps": true,
                  "InstanceFleets": [
                    {
                      "Name": "Master",
                      "InstanceFleetType": "MASTER",
                      "TargetOnDemandCapacity": 1,
                      "InstanceTypeConfigs": [
                        {"InstanceType": "m4.large"}
                      ]
                    }
                  ]
                },
                "VisibleToAllUsers": true,
                "ServiceRole": "${EMRClusterServiceRole}",
                "JobFlowRole": "${EMRClusterinstanceProfile}",
                "LogUri": "s3://${EMRClusterLogs}/",
                "Tags": [
                  { "Key": "Example", "Value": "${AWS::StackName}" }
                ]
              },
              "ResultSelector": {
                "ClusterId.$": "$.ClusterId"
              },
              "ResultPath": "$.Cluster",
              "Catch": [{
                "ErrorEquals": ["States.TaskFailed"],
                "Next": "Log Error"
              }],
              "Next": "Get StepExists"
            },

            "Get StepExists": {
              "Type": "Task",
              "Resource": "${GetStepExistsFunction.Arn}",
              "Catch": [{
                "ErrorEquals": ["States.TaskFailed"],
                "Next": "Log Error"
              }],
              "ResultPath": "$.Step",
              "Next": "Check StepExists"
            },

            "Check StepExists": {
              "Type": "Choice",
              "Choices": [{
                "Variable": "$.Error",
                "IsPresent": true,
                "Next": "Fail StepExistsScript"
              },{
                "Not": {
                  "Variable": "$.Step.StepId",
                  "StringEquals": ""
                },
                "Next": "Fail Step Already Exists"
              }],
              "Default": "Run Load"
            },

            "Fail StepExistsScript": {
              "Type": "Fail",
              "Error": "Get Step Exists",
              "Cause": "Please, check the EMAIL for error message."
            },

            "Fail Step Already Exists": {
              "Type": "Fail",
              "Error": "Step Already Exists",
              "Cause": "A Step with same name is active. Wait the active step complete before start a new step."
            },

            "Run Load": {
              "Type": "Task",
              "Resource": "arn:aws:states:::elasticmapreduce:addStep.sync",
              "Parameters": {
                "ClusterId.$": "$.Cluster.ClusterId",
                "Step": {
                  "Name.$": "States.Format('{}.{}',$.input1,$.input2)",
                  "HadoopJarStep": {
                    "Jar": "command-runner.jar",
                    "Args.$": "States.Array('spark-submit','s3://${ArtifactsBucket}/hello_world.py','${AWS::StackName}','${SNSError}',$.input1,$.input2)"
                  },
                  "ActionOnFailure": "CONTINUE"
                }
              },
              "ResultSelector": {
                "StepId.$": "$.StepId"
              },
              "ResultPath": "$.Step",
              "Catch": [{
                "ErrorEquals": ["States.TaskFailed"],
                "Next": "Log Error"
              }],
              "Next": "Check Keep"
            },

            "Check Keep": {
              "Type": "Choice",
              "Choices": [{
                "Variable": "$.KeepCluster",
                "BooleanEquals": true,
                "Next": "Succeed"
              }],
              "Default": "Wait"
            },

            "Wait": {
              "Type": "Wait",
              "Seconds": 10,
              "Next": "Get StepCount"
            },

            "Get StepCount": {
              "Type": "Task",
              "Resource": "${GetStepCountFunction.Arn}",
              "Catch": [{
                "ErrorEquals": ["States.TaskFailed"],
                "Next": "Log Error"
              }],
              "ResultPath": "$.Step",
              "Next": "Check StepCount"
            },

            "Check StepCount": {
              "Type": "Choice",
              "Choices": [{
                "Variable": "$.Error",
                "IsPresent": true,
                "Next": "Fail StepCount"
              },{
                "Variable": "$.Step.StepCount",
                "NumericEquals": 0,
                "Next": "Terminate Cluster"
              }],
              "Default": "Succeed"
            },

            "Fail StepCount": {
              "Type": "Fail",
              "Error": "Get Step Task",
              "Cause": "Please, check the EMAIL for error message."
            },

            "Terminate Cluster": {
              "Type": "Task",
              "Resource": "arn:aws:states:::elasticmapreduce:terminateCluster",
              "Parameters": {
                "ClusterId.$": "$.Cluster.ClusterId"
              },
              "ResultSelector": "",
              "Catch": [{
                "ErrorEquals": ["States.TaskFailed"],
                "Next": "Log Error"
              }],
              "Next": "Succeed"
            },

            "Succeed": {
              "Type": "Succeed"
            },

            "Log Error": {
              "Type": "Task",
              "Resource": "arn:aws:states:::sns:publish",
              "Parameters": {
                "TopicArn": "${SNSError}",
                "Subject.$": "States.Format('ERROR {}.{} Step Function ${AWS::StackName}',$.input1,$.input2)",
                "Message.$": "$"
              },
              "Next": "Fail Log Error"
            },

            "Fail Log Error": {
              "Type": "Fail",
              "Error": "Step Function Task",
              "Cause": "Please, check the EMAIL for error message."
            }

          }
        }
      RoleArn: !Sub ${StepFunctionRole.Arn}
      Tags:
        - Key: Example
          Value: !Ref AWS::StackName

Outputs:

  StepFunctionArn:
    Value: !Ref StepFunction
